Repository Abel13/4dinha, pull requests merged in 2025-02, with the labels that each got.

#20 feat: add vibration on player's turn (#1)
  components/TableSeat.tsx
  hooks/useSettingsStore.ts
  hooks/useVibration.ts
Labels: enhancement

#33 24 expo keep awake
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  app/(game)/4dinha/end.tsx
  app/(game)/4dinha/index.tsx
  app/(game)/4dinha/indiozinho.tsx
  app/(tabs)/index.tsx
  app/_layout.tsx
  app/lobby/[matchId].tsx
  components/Collapsible.tsx
  components/HapticTab.tsx
  components/MatchItem.tsx
  components/__tests__/ThemedText-test.tsx
  components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  components/ui/IconSymbol.ios.tsx
  components/ui/IconSymbol.tsx
  constants/Colors.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#35 fix: removed useMatch from item and created useDiceBear to create pi…
  components/MatchItem.tsx
  hooks/useDiceBear.ts
  hooks/useMatch.ts
  hooks/usePlayer.ts
  hooks/useUserSessionStore.ts
Labels: bug

#38 27 New game screen
  .gitignore
  app.json
  app/(game)/4dinha/_layout.tsx
  app/(game)/4dinha/end.tsx
  app/(game)/4dinha/index.tsx
  app/(game)/4dinha/indiozinho.tsx
  app/(tabs)/index.tsx
  app/+not-found.tsx
  app/auth/index.tsx
  app/lobby/[matchId].tsx
  app/lobby/_layout.tsx
  components/Bet.tsx
  components/Card.tsx
  components/MatchItem.tsx
  components/MenuIcon.tsx
  components/PlayerItem.tsx
  components/ResultItem.tsx
  components/StatusPanel.tsx
  components/Table/TableCards.tsx
  components/Table/TablePlayer.tsx
  components/Table/TableSeat.tsx
  components/TableSeat.tsx
  components/ThemedButton.tsx
  components/ThemedInput.tsx
  components/ThemedText.tsx
  constants/Colors.ts
  hooks/useTableSeat.ts
  package-lock.json
  package.json
  utils/scalingUtils.ts
Labels: enhancement

#40 feat: added update workflow
  .github/workflows/expo-update.yml
Labels: eas-build
